#!/usr/bin/env python3
"""Generates the default ExoBlackSmith item/recipe configs and the ItemsAdder content file.

Textures are read verbatim from tools/texture-registry.json (extracted from the development prompt), so
they are never retyped by hand. Run from the project root:  python3 tools/generate_configs.py
"""
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RES = os.path.join(ROOT, "src", "main", "resources")
IA = os.path.join(ROOT, "itemsadder", "contents", "exoblacksmith", "configs")
REG = json.load(open(os.path.join(ROOT, "tools", "texture-registry.json")))

HEADER = "# Generated by tools/generate_configs.py; safe to edit by hand on your server.\n"


def q(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'


# ------------------------------------------------------------------ heads
MOBS = {
    "sheep_value_head": ("SHEEP", "sheep", "uncommon", 0.05),
    "pig_value_head": ("PIG", "pig", "uncommon", 0.05),
    "polar_bear_value_head": ("POLAR_BEAR", "polar bear", "rare", 0.04),
    "zombie_value_head": ("ZOMBIE", "zombie", "uncommon", 0.05),
    "skeleton_value_head": ("SKELETON", "skeleton", "uncommon", 0.05),
    "creeper_value_head": ("CREEPER", "creeper", "uncommon", 0.05),
    "spider_value_head": ("SPIDER", "spider", "uncommon", 0.05),
    "wolf_value_head": ("WOLF", "wolf", "rare", 0.04),
    "villager_value_head": ("VILLAGER", "villager", "rare", 0.03),
    "iron_golem_value_head": ("IRON_GOLEM", "iron golem", "rare", 0.04),
    "stray_value_head": ("STRAY", "stray", "rare", 0.04),
    "drowned_value_head": ("DROWNED", "drowned", "rare", 0.04),
}
MASK_NAME = {e["head"]: e["mask"].lower() for e in REG}

out = [HEADER, "# Mob value heads: crafting ingredients. Textures are presentation only; identity is the signed item data.\n",
       "heads:\n"]
for e in REG:
    hid = e["head"]
    mob, label, rarity, chance = MOBS[hid]
    out.append(f"  {hid}:\n")
    out.append(f"    mob: {mob}\n")
    out.append(f"    name: {q(label + ' value head')}\n")
    out.append(f"    rarity: {rarity}\n")
    out.append(f"    material: PLAYER_HEAD\n")
    out.append(f"    texture: {q(e['head_texture'])}\n")
    out.append(f"    lore:\n")
    out.append(f"      - {q('<gray>a trophy taken from a ' + label + '.')}\n")
    out.append(f"      - {q('<dark_gray>used to forge the ' + MASK_NAME[hid] + ' mask, runes and upgrades.')}\n")
    out.append(f"    drop:\n      chance: {chance}\n      min: 1\n      max: 1\n")
open(os.path.join(RES, "heads.yml"), "w").write("".join(out))

# ------------------------------------------------------------------ masks
RAR = {1: "epic", 2: "legendary", 3: "fabled"}


def eff(t, a):
    return {"type": t, "amplifier": a}


MASKS = {
    "sedge": {"levels": [{"effects": [eff("speed", 0)]}, {"effects": [eff("speed", 1)]}]},
    "wisdom": {"levels": [{"effects": [eff("haste", 0)]}, {"effects": [eff("haste", 1)]}]},
    "canapy": {"levels": [
        {"abilities": {"heal": {"hearts": 4, "cooldown": 40}}, "effect-lore": ["<dark_gray>▸</dark_gray> <white>heal 4 hearts</white>"]},
        {"abilities": {"heal": {"hearts": 7, "cooldown": 40}}, "effect-lore": ["<dark_gray>▸</dark_gray> <white>heal 7 hearts</white>"]},
        {"abilities": {"heal": {"full": True, "cooldown": 40}}, "effect-lore": ["<dark_gray>▸</dark_gray> <white>restore full health</white>"]},
    ]},
    "trident": {"levels": [{"trident-bonus-damage": 1}, {"trident-bonus-damage": 2}, {"trident-bonus-damage": 3}]},
    "skelly": {"levels": [{"abilities": {"arrow-teleport": {"cooldown": 40, "miss-cooldown": 10, "max-flight-seconds": 8}},
                           "effect-lore": ["<dark_gray>▸</dark_gray> <white>teleport to your marked arrow</white>"]}]},
    "creepy": {"levels": [
        {"abilities": {"explosive-hit": {"bonus-damage": 2, "cooldown": 8}}, "effect-lore": ["<dark_gray>▸</dark_gray> <white>+2 explosive damage on player hits</white>"]},
        {"abilities": {"explosive-hit": {"bonus-damage": 4, "cooldown": 8}}, "effect-lore": ["<dark_gray>▸</dark_gray> <white>+4 explosive damage on player hits</white>"]},
    ]},
    "syder": {"levels": [
        {"abilities": {"cobweb": {"cooldown": 30, "shape": "plus", "duration-seconds": 6, "range": 12}}, "effect-lore": ["<dark_gray>▸</dark_gray> <white>web the targeted ground</white>"]},
        {"abilities": {"cobweb": {"cooldown": 20, "shape": "plus", "duration-seconds": 6, "range": 12}}, "effect-lore": ["<dark_gray>▸</dark_gray> <white>web the targeted ground</white>"]},
    ]},
    "wolfski": {"levels": [{"abilities": {"summon": {"entity": "WOLF", "count": 2, "lifetime-seconds": 15, "cooldown": 45, "range": 16, "damage": 4}},
                            "effect-lore": ["<dark_gray>▸</dark_gray> <white>summon 2 wolves at your target</white>"]}]},
    "guard": {"levels": [
        {"abilities": {"summon": {"entity": "IRON_GOLEM", "count": 1, "lifetime-seconds": 15, "cooldown": 60, "range": 16, "damage": 6}}, "effect-lore": ["<dark_gray>▸</dark_gray> <white>summon an iron golem at your target</white>"]},
        {"abilities": {"summon": {"entity": "IRON_GOLEM", "count": 2, "lifetime-seconds": 15, "cooldown": 60, "range": 16, "damage": 6}}, "effect-lore": ["<dark_gray>▸</dark_gray> <white>summon 2 iron golems at your target</white>"]},
    ]},
    "golom": {"levels": [
        {"effects": [eff("regeneration", 0), eff("strength", 0)], "bonus-hearts": 3},
        {"effects": [eff("regeneration", 0), eff("strength", 0)], "bonus-hearts": 4},
        {"effects": [eff("regeneration", 1), eff("strength", 0)], "bonus-hearts": 5},
    ]},
    "stray": {"levels": [
        {"effects": [eff("speed", 0), eff("strength", 0)], "bonus-hearts": 2},
        {"effects": [eff("speed", 0), eff("strength", 0)], "bonus-hearts": 3},
        {"effects": [eff("speed", 1), eff("strength", 0)], "bonus-hearts": 4},
    ]},
    "drownie": {"levels": [
        {"effects": [eff("strength", 0), eff("regeneration", 0)], "bonus-hearts": 8, "trident-bonus-damage": 1,
         "abilities": {"cobweb": {"cooldown": 30, "shape": "plus", "duration-seconds": 6, "range": 12}}, "effect-lore": ["<dark_gray>▸</dark_gray> <white>web the targeted ground</white>"]},
        {"effects": [eff("strength", 0), eff("regeneration", 0)], "bonus-hearts": 9, "trident-bonus-damage": 2,
         "abilities": {"cobweb": {"cooldown": 30, "shape": "plus", "duration-seconds": 6, "range": 12}}, "effect-lore": ["<dark_gray>▸</dark_gray> <white>web the targeted ground</white>"]},
        {"effects": [eff("strength", 0), eff("regeneration", 0)], "bonus-hearts": 10, "trident-bonus-damage": 3,
         "abilities": {"cobweb": {"cooldown": 30, "shape": "plus", "duration-seconds": 6, "range": 12}}, "effect-lore": ["<dark_gray>▸</dark_gray> <white>web the targeted ground</white>"]},
    ]},
}
FLAVOR = {
    "sedge": "woven from sheep wool and swiftness.", "wisdom": "a pig's patient focus.",
    "canapy": "a polar bear's warmth that mends wounds.", "trident": "the drowned dead's grip on the trident.",
    "skelly": "a skeleton's eye for the arrow's path.", "creepy": "a creeper's spark in every strike.",
    "syder": "a spider's patience in silk.", "wolfski": "the pack answers your call.",
    "guard": "the village guardians stand with you.", "golom": "the iron golem's unyielding body.",
    "stray": "frost-bitten vigour of the stray.", "drownie": "the depths' strength and snaring nets.",
}


def yaml_value(v, indent):
    pad = " " * indent
    if isinstance(v, dict):
        s = "\n"
        for k, val in v.items():
            s += f"{pad}{k}:" + yaml_value(val, indent + 2)
        return s
    if isinstance(v, list):
        s = "\n"
        for item in v:
            if isinstance(item, dict):
                first = True
                for k, val in item.items():
                    s += (f"{pad}- " if first else f"{pad}  ") + f"{k}:" + yaml_value(val, indent + 4)
                    first = False
            else:
                s += f"{pad}- {yaml_scalar(item)}\n"
        return s
    return " " + yaml_scalar(v) + "\n"


def yaml_scalar(v):
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    return q(str(v))


out = [HEADER,
       "# Masks are custom player heads worn in the helmet slot. Effects work only while worn there.\n",
       "# Ability controls: sneak + right-click (heal, cobweb, summon); sneak while firing a bow (arrow teleport).\n",
       "# Values marked as proposals in the README are balancing choices; change them freely.\n",
       "masks:\n"]
for e in REG:
    mid = e["mask"].lower()
    m = MASKS[mid]
    out.append(f"  {mid}:\n")
    out.append(f"    name: {q(mid + ' mask')}\n")
    out.append(f"    ingredient-head: {e['head']}\n")
    out.append(f"    material: PLAYER_HEAD\n")
    out.append(f"    texture: {q(e['mask_texture'])}\n")
    out.append(f"    lore:\n      - {q('<gray>' + FLAVOR[mid])}\n")
    out.append(f"    levels:\n")
    for i, level in enumerate(m["levels"], start=1):
        data = {"rarity": RAR[i] if len(m["levels"]) > 1 else "epic"}
        data.update(level)
        out.append(f"      {i}:" + yaml_value(data, 8))
open(os.path.join(RES, "masks.yml"), "w").write("".join(out))

# ------------------------------------------------------------------ runes
RUNES = [
    ("blast_rune", "blast rune", "BLAST", "ANY", "minecraft:fire_charge", (0.15, 0.20, 0.25),
     "<dark_gray>▸</dark_gray> <white>-{value}</white> <gray>damage from end crystals & respawn anchors", {}),
    ("totem_surge", "totem surge rune", "TOTEM_SURGE", "CHESTPLATE", "minecraft:totem_of_undying", (2, 3, 4),
     "<dark_gray>▸</dark_gray> <gray>on totem pop:</gray> <white>{value} invisibility + dash", {"dash-force": 1.4, "dash-vertical": 0.35, "cooldown": 30}),
    ("hardened_shell", "hardened shell rune", "HARDENED_SHELL", "ANY", "minecraft:turtle_scute", (0.12, 0.16, 0.20),
     "<dark_gray>▸</dark_gray> <white>-{value}</white> <gray>critical sword & axe damage", {}),
    ("kinetic_reducer", "kinetic reducer rune", "KINETIC_REDUCER", "ANY", "minecraft:wind_charge", (0.20, 0.30, 0.40),
     "<dark_gray>▸</dark_gray> <white>-{value}</white> <gray>mace smash & elytra collision damage", {}),
    ("phoenix_aura", "phoenix aura rune", "PHOENIX_AURA", "CHESTPLATE", "minecraft:blaze_powder", (0.30, 0.40, 0.50),
     "<dark_gray>▸</dark_gray> <white>-{value}</white> <gray>fire & lava damage, burning ends within 1s", {}),
    ("void_stride", "void stride rune", "VOID_STRIDE", "BOOTS", "minecraft:ender_eye", (0.10, 0.15, 0.20),
     "<dark_gray>▸</dark_gray> <white>+{value}</white> <gray>walking speed, no soul sand slowdown", {}),
    ("feather_ward", "feather ward rune", "FEATHER_WARD", "BOOTS", "minecraft:feather", (0.10, 0.20, 0.30),
     "<dark_gray>▸</dark_gray> <white>-{value}</white> <gray>fall damage", {}),
    ("anchor_guard", "anchor guard rune", "ANCHOR_GUARD", "LEGGINGS", "minecraft:heavy_core", (0.10, 0.15, 0.20),
     "<dark_gray>▸</dark_gray> <white>+{value}</white> <gray>knockback resistance", {}),
    ("tidal_breath", "tidal breath rune", "TIDAL_BREATH", "HELMET", "minecraft:heart_of_the_sea", (10, 20, 30),
     "<dark_gray>▸</dark_gray> <white>{value}</white> <gray>water breathing when submerged", {"cooldown": 60}),
]
out = [HEADER,
       "# Runes: three tiers each. mechanic is the hard-coded behaviour; values are configurable.\n",
       "# Reduction values are fractions (0.15 = 15%). totem_surge/tidal_breath values are seconds.\n",
       "runes:\n"]
for rid, name, mech, slot, model, values, line, params in RUNES:
    out.append(f"  {rid}:\n    name: {q(name)}\n    mechanic: {mech}\n    slot: {slot}\n")
    out.append(f"    material: PAPER\n    item-model: {q(model)}\n    glint: true\n    itemsadder-id: {q('exoblacksmith:' + rid)}\n")
    out.append(f"    effect-line: {q(line)}\n")
    out.append(f"    lore:\n      - {q('<gray>socket into exoblacksmith armor at the rune forge.')}\n")
    out.append("    tiers:\n")
    for i, v in enumerate(values, start=1):
        out.append(f"      {i}:\n        rarity: {RAR[i]}\n        value: {v}\n")
    if params:
        out.append("    params:\n")
        for k, v in params.items():
            out.append(f"      {k}: {v}\n")
open(os.path.join(RES, "runes.yml"), "w").write("".join(out))

# ------------------------------------------------------------------ armor
PIECES = [("helmet", "HELMET"), ("chestplate", "CHESTPLATE"), ("leggings", "LEGGINGS"), ("boots", "BOOTS")]
SETS = {
    "emberforged": {
        "rarity": "epic", "head": "pig_value_head", "edge": ("minecraft:blaze_rod", 8),
        "reductions": [("FIRE", 0.06), ("LAVA", 0.06)], "speed": {},
        "bonus": [("FIRE", 0.10), ("LAVA", 0.10)], "bonus_speed": 0,
        "ability": {"name": "ember ward", "type": "WARD", "cooldown": 90, "duration": 6, "extinguish": True,
                    "reductions": [("FIRE", 0.40), ("LAVA", 0.40)],
                    "lore": ["<dark_gray>  -40% fire & lava damage for {duration}, extinguishes you"]},
        "flavor": "forged in the nether's breath.",
    },
    "riftguard": {
        "rarity": "epic", "head": "creeper_value_head", "edge": ("minecraft:crying_obsidian", 8),
        "reductions": [("EXPLOSION", 0.05)], "speed": {},
        "bonus": [("CRYSTAL_ANCHOR", 0.10)], "bonus_speed": 0,
        "ability": {"name": "rift barrier", "type": "WARD", "cooldown": 75, "duration": 3, "extinguish": False,
                    "reductions": [("ALL", 0.30)],
                    "lore": ["<dark_gray>  -30% all damage for {duration}"]},
        "flavor": "tempered against crystal and anchor.",
    },
    "stormstride": {
        "rarity": "epic", "head": "stray_value_head", "edge": ("minecraft:breeze_rod", 6),
        "reductions": [("FALL", 0.08), ("ELYTRA_COLLISION", 0.08)], "speed": {"boots": 0.04},
        "bonus": [("MACE_SMASH", 0.08)], "bonus_speed": 0.05,
        "ability": {"name": "gale step", "type": "DASH", "cooldown": 45, "duration": 3, "extinguish": False,
                    "dash-force": 1.3, "dash-vertical": 0.35, "reductions": [("FALL", 0.60)],
                    "lore": ["<dark_gray>  dash forward, -60% fall damage for {duration}"]},
        "flavor": "light as the storm, steady as stone.",
    },
}
out = [HEADER,
       "# Custom armor. Base armor points/toughness come from the vanilla material.\n",
       "# Set bonuses need the slots in required-slots (default chestplate + leggings + boots, so a mask can be worn).\n",
       "# Set ability control: sneak + swap-hands key (F).\n",
       "sets:\n"]
for sid, s in SETS.items():
    out.append(f"  {sid}:\n    name: {q(sid)}\n    required-slots: [CHESTPLATE, LEGGINGS, BOOTS]\n    bonus:\n")
    out.append("      reductions:\n")
    for c, v in s["bonus"]:
        out.append(f"        - {{category: {c}, value: {v}}}\n")
    out.append(f"      speed: {s['bonus_speed']}\n")
    a = s["ability"]
    out.append(f"    ability:\n      name: {q(a['name'])}\n      type: {a['type']}\n      cooldown: {a['cooldown']}\n      duration: {a['duration']}\n")
    out.append(f"      extinguish: {'true' if a['extinguish'] else 'false'}\n")
    if a["type"] == "DASH":
        out.append(f"      dash-force: {a['dash-force']}\n      dash-vertical: {a['dash-vertical']}\n")
    out.append("      reductions:\n")
    for c, v in a["reductions"]:
        out.append(f"        - {{category: {c}, value: {v}}}\n")
    out.append("      lore:\n")
    for l in a["lore"]:
        out.append(f"        - {q(l)}\n")
out.append("pieces:\n")
for sid, s in SETS.items():
    for piece, slot in PIECES:
        pid = f"{sid}_{piece}"
        out.append(f"  {pid}:\n    name: {q(sid + ' ' + piece)}\n    set: {sid}\n    slot: {slot}\n    rarity: {s['rarity']}\n")
        out.append(f"    material: DIAMOND_{piece.upper()}\n    itemsadder-id: {q('exoblacksmith:' + pid)}\n")
        out.append(f"    lore:\n      - {q('<gray>' + s['flavor'])}\n")
        out.append("    reductions:\n")
        for c, v in s["reductions"]:
            out.append(f"      - {{category: {c}, value: {v}}}\n")
        if piece in s["speed"]:
            out.append(f"    speed: {s['speed'][piece]}\n")
open(os.path.join(RES, "armor.yml"), "w").write("".join(out))

# ------------------------------------------------------------------ upgrades
UPGRADABLE = [e["mask"].lower() for e in REG if len(MASKS[e["mask"].lower()]["levels"]) > 1]
out = [HEADER, "# Rune upgrade materials and mask totems. Totems use a non-functional base material with a\n",
       "# totem item model, so they are never consumed as real Totems of Undying.\n",
       "materials:\n",
       "  legendary_rune_upgrade:\n    name: \"legendary rune upgrade\"\n    rarity: legendary\n    material: PAPER\n",
       "    item-model: \"minecraft:echo_shard\"\n    glint: true\n    itemsadder-id: \"exoblacksmith:legendary_rune_upgrade\"\n",
       "    lore:\n      - \"<gray>120 of these raise a rune from tier i to tier ii.\"\n",
       "  fabled_rune_upgrade:\n    name: \"fabled rune upgrade\"\n    rarity: fabled\n    material: PAPER\n",
       "    item-model: \"minecraft:nether_star\"\n    glint: true\n    itemsadder-id: \"exoblacksmith:fabled_rune_upgrade\"\n",
       "    lore:\n      - \"<gray>120 of these raise a rune from tier ii to tier iii.\"\n",
       "totems:\n"]
for mid in UPGRADABLE:
    tid = f"{mid}_mask_totem"
    out.append(f"  {tid}:\n    name: {q(mid + ' mask totem')}\n    mask: {mid}\n    rarity: legendary\n    material: PAPER\n")
    out.append(f"    item-model: \"minecraft:totem_of_undying\"\n    glint: true\n    itemsadder-id: {q('exoblacksmith:' + tid)}\n")
    out.append(f"    lore:\n      - {q('<gray>upgrades the ' + mid + ' mask by one level.')}\n      - \"<dark_gray>only works on its own mask.\"\n")
open(os.path.join(RES, "upgrades.yml"), "w").write("".join(out))

# ------------------------------------------------------------------ recipes
R = [HEADER,
     "# Blacksmith recipes. pattern is the 3x3 grid (space = empty); key maps symbols to ingredients.\n",
     "# Ingredients are taken by total quantity from the player's inventory when they press craft.\n",
     "# Plugin items: item: <id> (+ tier/level). Vanilla items: item: minecraft:<id> (must be plain, unrenamed).\n",
     "# Every quantity below is a proposed balancing default unless the README marks it as specified.\n",
     "recipes:\n"]


def recipe(rid, category, out_item, out_level, out_amount, pattern, key):
    R.append(f"  {rid}:\n    category: {category}\n    output:\n      item: {out_item}\n")
    if out_level > 1:
        R.append(f"      tier: {out_level}\n")
    if out_amount != 1:
        R.append(f"      amount: {out_amount}\n")
    R.append("    pattern:\n")
    for row in pattern:
        R.append(f"      - {q(row)}\n")
    R.append("    key:\n")
    for sym, (item, amount, level) in key.items():
        lvl = f", tier: {level}" if level and level > 1 else ""
        R.append(f"      {sym}: {{item: {item}, amount: {amount}{lvl}}}\n")


# armor
for sid, s in SETS.items():
    for piece, slot in PIECES:
        recipe(f"{sid}_{piece}", "armor", f"{sid}_{piece}", 1, 1, ["HEH", "EXE", "HEH"],
               {"H": (s["head"], 4, 1), "E": (s["edge"][0], s["edge"][1], 1), "X": (f"minecraft:diamond_{piece}", 1, 1)})
# masks
for e in REG:
    mid = e["mask"].lower()
    recipe(f"{mid}_mask", "masks", mid, 1, 1, ["HHH", "HCH", "HHH"],
           {"H": (e["head"], 8, 1), "C": ("minecraft:diamond_block", 1, 1)})
# runes tier 1: corners A, edges B (distinct pair per rune)
RUNE_HEADS = {
    "blast_rune": ("creeper_value_head", "skeleton_value_head"),
    "totem_surge": ("villager_value_head", "zombie_value_head"),
    "hardened_shell": ("iron_golem_value_head", "zombie_value_head"),
    "kinetic_reducer": ("stray_value_head", "spider_value_head"),
    "phoenix_aura": ("pig_value_head", "creeper_value_head"),
    "void_stride": ("wolf_value_head", "spider_value_head"),
    "feather_ward": ("sheep_value_head", "skeleton_value_head"),
    "anchor_guard": ("iron_golem_value_head", "villager_value_head"),
    "tidal_breath": ("drowned_value_head", "polar_bear_value_head"),
}
pairs = [frozenset(v) for v in RUNE_HEADS.values()]
assert len(set(pairs)) == len(pairs), "rune head combinations must be distinct"
for rid, (a, b) in RUNE_HEADS.items():
    recipe(rid, "runes", rid, 1, 1, ["ABA", "B B", "ABA"], {"A": (a, 15, 1), "B": (b, 15, 1)})
# upgrade materials
recipe("legendary_rune_upgrade", "upgrades", "legendary_rune_upgrade", 1, 8, ["ZGZ", "GDG", "ZGZ"],
       {"Z": ("zombie_value_head", 2, 1), "G": ("minecraft:gold_ingot", 4, 1), "D": ("minecraft:diamond", 1, 1)})
recipe("fabled_rune_upgrade", "upgrades", "fabled_rune_upgrade", 1, 8, ["KLK", "LNL", "KLK"],
       {"K": ("iron_golem_value_head", 2, 1), "L": ("legendary_rune_upgrade", 4, 1), "N": ("minecraft:netherite_scrap", 1, 1)})
# rune upgrades (specified: 120 upgrade items around the rune)
for rid in RUNE_HEADS:
    recipe(f"{rid}_tier_2", "upgrades", rid, 2, 1, ["UUU", "URU", "UUU"],
           {"U": ("legendary_rune_upgrade", 15, 1), "R": (rid, 1, 1)})
    recipe(f"{rid}_tier_3", "upgrades", rid, 3, 1, ["UUU", "URU", "UUU"],
           {"U": ("fabled_rune_upgrade", 15, 1), "R": (rid, 1, 2)})
# mask totems + mask upgrades
HEAD_OF = {e["mask"].lower(): e["head"] for e in REG}
for mid in UPGRADABLE:
    recipe(f"{mid}_mask_totem", "upgrades", f"{mid}_mask_totem", 1, 1, ["GHG", "HTH", "GHG"],
           {"G": ("minecraft:gold_block", 1, 1), "H": (HEAD_OF[mid], 4, 1), "T": ("minecraft:totem_of_undying", 1, 1)})
    for level in range(1, len(MASKS[mid]["levels"])):
        recipe(f"{mid}_mask_level_{level + 1}", "upgrades", mid, level + 1, 1, ["HTH", "HMH", "HHH"],
               {"H": (HEAD_OF[mid], 15, 1), "T": (f"{mid}_mask_totem", 1, 1), "M": (mid, 1, level)})
open(os.path.join(RES, "recipes.yml"), "w").write("".join(R))

# ------------------------------------------------------------------ ItemsAdder content (UNVERIFIED format; see README)
os.makedirs(IA, exist_ok=True)
ia = ["# ItemsAdder content for ExoBlackSmith visuals. Written from ItemsAdder 4.x conventions; the docs\n",
      "# site was not reachable while building, so verify the keys against your ItemsAdder version.\n",
      "# ExoBlackSmith copies only item_model / custom model data / equippable from these items.\n",
      "info:\n  namespace: exoblacksmith\n\nitems:\n"]


def ia_item(iid, display, material, texture, equipment=None):
    ia.append(f"  {iid}:\n    display_name: {q(display)}\n    resource:\n      material: {material}\n      generate: true\n")
    ia.append(f"      textures:\n        - {q('item/' + texture + '.png')}\n")
    if equipment:
        ia.append(f"    equipment:\n      id: {q('exoblacksmith:' + equipment)}\n")


for rid, name, *_ in RUNES:
    ia_item(rid, name, "PAPER", f"runes/{rid}")
ia_item("legendary_rune_upgrade", "legendary rune upgrade", "PAPER", "upgrades/legendary_rune_upgrade")
ia_item("fabled_rune_upgrade", "fabled rune upgrade", "PAPER", "upgrades/fabled_rune_upgrade")
for mid in UPGRADABLE:
    ia_item(f"{mid}_mask_totem", f"{mid} mask totem", "PAPER", f"totems/{mid}_mask_totem")
for sid in SETS:
    for piece, slot in PIECES:
        ia_item(f"{sid}_{piece}", f"{sid} {piece}", f"DIAMOND_{piece.upper()}", f"armor/{sid}_{piece}", sid)
ia.append("\nequipments:\n")
for sid in SETS:
    ia.append(f"  {sid}:\n    type: armor\n    layer_1: {q('armor/' + sid + '_layer_1')}\n    layer_2: {q('armor/' + sid + '_layer_2')}\n")
ia.append("\nfont_images:\n")
for r in ["common", "uncommon", "rare", "epic", "legendary", "fabled"]:
    ia.append(f"  rarity_{r}:\n    path: {q('font/rarity_' + r + '.png')}\n    y_position: 8\n    scale_ratio: 9\n")
open(os.path.join(IA, "exoblacksmith.yml"), "w").write("".join(ia))
print("generated: heads, masks, runes, armor, upgrades, recipes, itemsadder config;",
      len(UPGRADABLE), "totems")
